# Generated by Django 4.2.16 on 2024-10-23 08:41

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='presentation',
            field=models.FileField(upload_to='lessons/', validators=[main_app.models.validate_pptx]),
        ),
    ]
