# Generated by Django 4.2.16 on 2024-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_student_alter_attendance_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_class',
            field=models.BooleanField(default=False),
        ),
    ]
