# Generated by Django 4.2.16 on 2024-10-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('education', models.TextField(verbose_name='Образование')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Страница "Обо мне"',
                'verbose_name_plural': 'Страница "Обо мне"',
            },
        ),
        migrations.CreateModel(
            name='TeacherResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на ресурс')),
                ('file', models.FileField(blank=True, null=True, upload_to='teacher_resources/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Ресурс для учителей',
                'verbose_name_plural': 'Ресурсы для учителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
