# Generated by Django 4.2.16 on 2024-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_student_activated',
            field=models.BooleanField(default=False),
        ),
    ]
