# Generated by Django 4.2.16 on 2024-10-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0013_userprofile_is_student_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(verbose_name='Идея')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Идея пользователя',
                'verbose_name_plural': 'Идеи пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
