# Generated by Django 4.2 on 2024-10-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_add_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherresource',
            name='link',
        ),
    ]
